runtime: python39
service: website-static # Ganti dengan nama layanan yang Anda inginkan

handlers:
  - url: /
    static_files: www/index.html
    upload: www/index.html

  - url: /images
    static_dir: www/images
